name: Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: "/opt/termux/android-sdk"
      NDK: "/opt/termux/android-ndk"
    strategy:
      matrix:
        target_arch: [aarch64, arm, i686, x86_64]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: termux/termux-packages
          fetch-depth: 1000
      - name: Clone nginx-rtmp
        uses: actions/checkout@v2
        with:
          path: packages/nginx-rtmp
      - name: Configure environment
        run: |
          ls packages/nginx-rtmp
          ./scripts/setup-ubuntu.sh
          ./scripts/setup-android-sdk.sh
      - name: Build
        run: |
          ./build-package.sh -I nginx-rtmp
          ls debs
